import Head from 'next/head'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://docs.manifold.xyz/v/manifold-for-developers/client-widgets/overview">
            Manifold
          </a>
          <span> </span>
          Next.js Template
        </h1>
        <br />

        {/* -- Add Connect Widget -- */}
        <div dangerouslySetInnerHTML={{ 
          __html: 
            "<div \
              data-widget='m-connect' \
              data-app-name='dgSig' \
              data-app-name='{process.env.DATA_APP_NAME}' \
              data-client-id='{process.env.DATA_CLIENT_ID}' \
              data-network='{process.env.DATA_NETWORK}' \
            ></div>"
        }} />

        {/* ~~ Add Marketplace Widget component ~~ */}
        <div dangerouslySetInnerHTML={{ 
          __html: 
            "<div \
              data-widget='m-layout-complete-listing' \
              data-id='444' \
              data-network='1' \
            ></div>"
        }} />
      </main>
    </div>
  )
}
