import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Listing from '../components/Listing'
import Connect from '../components/Connect'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Claim - Next example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://docs.manifold.xyz/v/manifold-for-developers/client-widgets/overview">
            Manifold
          </a>
          <span> </span>
          Next.js Template
        </h1>
        <br />

        {/* -- Add Connect Widget -- */}
        <Connect network={1} />

        {/* ~~ Add Claim Widget component ~~ */}
        <Listing id={1040586992} network={1} />
      </main>
    </div>
  )
}
